//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type for Collation with rail industry reference systems
 * 
 * <p>Java class for AnnotatedRailRefStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotatedRailRefStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}AnnotatedCrossRefStructure">
 *       &lt;sequence>
 *         &lt;element name="TiplocRef" type="{http://www.naptan.org.uk/}TiplocCodeType"/>
 *         &lt;element name="CrsRef" type="{http://www.naptan.org.uk/}CrsCodeType" minOccurs="0"/>
 *         &lt;element name="StationName" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure"/>
 *         &lt;element name="Location" type="{http://www.naptan.org.uk/}LocationStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotatedRailRefStructure", propOrder = {
    "tiplocRef",
    "crsRef",
    "stationName",
    "location"
})
public class AnnotatedRailRefStructure
    extends AnnotatedCrossRefStructure
{

    @XmlElement(name = "TiplocRef", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tiplocRef;
    @XmlElement(name = "CrsRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String crsRef;
    @XmlElement(name = "StationName", required = true)
    protected NaturalLanguageStringStructure stationName;
    @XmlElement(name = "Location")
    protected LocationStructure location;

    /**
     * Gets the value of the tiplocRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTiplocRef() {
        return tiplocRef;
    }

    /**
     * Sets the value of the tiplocRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTiplocRef(String value) {
        this.tiplocRef = value;
    }

    /**
     * Gets the value of the crsRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrsRef() {
        return crsRef;
    }

    /**
     * Sets the value of the crsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrsRef(String value) {
        this.crsRef = value;
    }

    /**
     * Gets the value of the stationName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getStationName() {
        return stationName;
    }

    /**
     * Sets the value of the stationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setStationName(NaturalLanguageStringStructure value) {
        this.stationName = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setLocation(LocationStructure value) {
        this.location = value;
    }

}
