//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Type for Collation with air industry reference systems
 * 
 * <p>Java class for AnnotatedAirRefStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotatedAirRefStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}AnnotatedCrossRefStructure">
 *       &lt;sequence>
 *         &lt;element name="IataRef" type="{http://www.naptan.org.uk/}IataCodeType"/>
 *         &lt;element name="Name" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotatedAirRefStructure", propOrder = {
    "iataRef",
    "name"
})
public class AnnotatedAirRefStructure
    extends AnnotatedCrossRefStructure
{

    @XmlElement(name = "IataRef", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String iataRef;
    @XmlElement(name = "Name", required = true)
    protected NaturalLanguageStringStructure name;

    /**
     * Gets the value of the iataRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIataRef() {
        return iataRef;
    }

    /**
     * Sets the value of the iataRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIataRef(String value) {
        this.iataRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setName(NaturalLanguageStringStructure value) {
        this.name = value;
    }

}
