//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Data type for an annotated reference to a stop that is defined elsewhere using a StopPointStructure. The annotation is the stop's common name. 
 * 
 * <p>Java class for AnnotatedStopPointRefStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotatedStopPointRefStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}VersionedChildStructure">
 *       &lt;sequence>
 *         &lt;element name="StopPointRef" type="{http://www.naptan.org.uk/}StopPointCodeType"/>
 *         &lt;element name="CommonName" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure"/>
 *         &lt;element name="Crossing" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
 *         &lt;element name="Street" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
 *         &lt;element name="Indicator" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure" minOccurs="0"/>
 *         &lt;element name="StopType" type="{http://www.naptan.org.uk/}StopTypeEnumeration" minOccurs="0"/>
 *         &lt;element name="BusStopType" type="{http://www.naptan.org.uk/}BusStopTypeEnumeration" minOccurs="0"/>
 *         &lt;element name="LocalityName" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *         &lt;element name="LocalityQualifier" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
 *         &lt;element name="Location" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.naptan.org.uk/}LocationStructure">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotatedStopPointRefStructure", propOrder = {
    "stopPointRef",
    "commonName",
    "crossing",
    "street",
    "indicator",
    "stopType",
    "busStopType",
    "localityName",
    "localityQualifier",
    "location"
})
@XmlSeeAlso({
    AnnotatedStopPointRef.class
})
public class AnnotatedStopPointRefStructure
    extends VersionedChildStructure
{

    @XmlElement(name = "StopPointRef", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String stopPointRef;
    @XmlElement(name = "CommonName", required = true)
    protected NaturalLanguageStringStructure commonName;
    @XmlElement(name = "Crossing")
    protected NaturalLanguagePlaceNameStructure crossing;
    @XmlElement(name = "Street")
    protected NaturalLanguagePlaceNameStructure street;
    @XmlElement(name = "Indicator")
    protected NaturalLanguagePlaceNameStructure indicator;
    @XmlElement(name = "StopType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stopType;
    @XmlElement(name = "BusStopType")
    protected BusStopTypeEnumeration busStopType;
    @XmlElement(name = "LocalityName")
    protected NaturalLanguageStringStructure localityName;
    @XmlElement(name = "LocalityQualifier")
    protected NaturalLanguageStringStructure localityQualifier;
    @XmlElement(name = "Location")
    protected AnnotatedStopPointRefStructure.Location location;

    /**
     * Gets the value of the stopPointRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopPointRef() {
        return stopPointRef;
    }

    /**
     * Sets the value of the stopPointRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopPointRef(String value) {
        this.stopPointRef = value;
    }

    /**
     * Gets the value of the commonName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getCommonName() {
        return commonName;
    }

    /**
     * Sets the value of the commonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setCommonName(NaturalLanguageStringStructure value) {
        this.commonName = value;
    }

    /**
     * Gets the value of the crossing property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public NaturalLanguagePlaceNameStructure getCrossing() {
        return crossing;
    }

    /**
     * Sets the value of the crossing property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public void setCrossing(NaturalLanguagePlaceNameStructure value) {
        this.crossing = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public NaturalLanguagePlaceNameStructure getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public void setStreet(NaturalLanguagePlaceNameStructure value) {
        this.street = value;
    }

    /**
     * Gets the value of the indicator property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public NaturalLanguagePlaceNameStructure getIndicator() {
        return indicator;
    }

    /**
     * Sets the value of the indicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public void setIndicator(NaturalLanguagePlaceNameStructure value) {
        this.indicator = value;
    }

    /**
     * Gets the value of the stopType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopType() {
        return stopType;
    }

    /**
     * Sets the value of the stopType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopType(String value) {
        this.stopType = value;
    }

    /**
     * Gets the value of the busStopType property.
     * 
     * @return
     *     possible object is
     *     {@link BusStopTypeEnumeration }
     *     
     */
    public BusStopTypeEnumeration getBusStopType() {
        return busStopType;
    }

    /**
     * Sets the value of the busStopType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusStopTypeEnumeration }
     *     
     */
    public void setBusStopType(BusStopTypeEnumeration value) {
        this.busStopType = value;
    }

    /**
     * Gets the value of the localityName property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getLocalityName() {
        return localityName;
    }

    /**
     * Sets the value of the localityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setLocalityName(NaturalLanguageStringStructure value) {
        this.localityName = value;
    }

    /**
     * Gets the value of the localityQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public NaturalLanguageStringStructure getLocalityQualifier() {
        return localityQualifier;
    }

    /**
     * Sets the value of the localityQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguageStringStructure }
     *     
     */
    public void setLocalityQualifier(NaturalLanguageStringStructure value) {
        this.localityQualifier = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedStopPointRefStructure.Location }
     *     
     */
    public AnnotatedStopPointRefStructure.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedStopPointRefStructure.Location }
     *     
     */
    public void setLocation(AnnotatedStopPointRefStructure.Location value) {
        this.location = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.naptan.org.uk/}LocationStructure">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Location
        extends LocationStructure
    {


    }

}
