//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for Type of Bus and Coach stop. 
 * 
 * <p>Java class for BusAndCoachStopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusAndCoachStopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *           &lt;element name="Bay">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="VariableBay">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusAndCoachStopClassificationStructure", propOrder = {
    "entrance",
    "accessArea",
    "bay",
    "variableBay",
    "annotatedCoachRef"
})
public class BusAndCoachStopClassificationStructure {

    @XmlElement(name = "Entrance")
    protected String entrance;
    @XmlElement(name = "AccessArea")
    protected String accessArea;
    @XmlElement(name = "Bay")
    protected BusAndCoachStopClassificationStructure.Bay bay;
    @XmlElement(name = "VariableBay")
    protected BusAndCoachStopClassificationStructure.VariableBay variableBay;
    @XmlElement(name = "AnnotatedCoachRef")
    protected List<AnnotatedCoachRefStructure> annotatedCoachRef;

    /**
     * Gets the value of the entrance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrance() {
        return entrance;
    }

    /**
     * Sets the value of the entrance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrance(String value) {
        this.entrance = value;
    }

    /**
     * Gets the value of the accessArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessArea() {
        return accessArea;
    }

    /**
     * Sets the value of the accessArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessArea(String value) {
        this.accessArea = value;
    }

    /**
     * Gets the value of the bay property.
     * 
     * @return
     *     possible object is
     *     {@link BusAndCoachStopClassificationStructure.Bay }
     *     
     */
    public BusAndCoachStopClassificationStructure.Bay getBay() {
        return bay;
    }

    /**
     * Sets the value of the bay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusAndCoachStopClassificationStructure.Bay }
     *     
     */
    public void setBay(BusAndCoachStopClassificationStructure.Bay value) {
        this.bay = value;
    }

    /**
     * Gets the value of the variableBay property.
     * 
     * @return
     *     possible object is
     *     {@link BusAndCoachStopClassificationStructure.VariableBay }
     *     
     */
    public BusAndCoachStopClassificationStructure.VariableBay getVariableBay() {
        return variableBay;
    }

    /**
     * Sets the value of the variableBay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusAndCoachStopClassificationStructure.VariableBay }
     *     
     */
    public void setVariableBay(BusAndCoachStopClassificationStructure.VariableBay value) {
        this.variableBay = value;
    }

    /**
     * Gets the value of the annotatedCoachRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotatedCoachRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotatedCoachRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotatedCoachRefStructure }
     * 
     * 
     */
    public List<AnnotatedCoachRefStructure> getAnnotatedCoachRef() {
        if (annotatedCoachRef == null) {
            annotatedCoachRef = new ArrayList<AnnotatedCoachRefStructure>();
        }
        return this.annotatedCoachRef;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timingStatus"
    })
    public static class Bay {

        @XmlElement(name = "TimingStatus")
        protected TimingStatusEnumeration timingStatus;

        /**
         * Gets the value of the timingStatus property.
         * 
         * @return
         *     possible object is
         *     {@link TimingStatusEnumeration }
         *     
         */
        public TimingStatusEnumeration getTimingStatus() {
            return timingStatus;
        }

        /**
         * Sets the value of the timingStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link TimingStatusEnumeration }
         *     
         */
        public void setTimingStatus(TimingStatusEnumeration value) {
            this.timingStatus = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timingStatus"
    })
    public static class VariableBay {

        @XmlElement(name = "TimingStatus")
        protected TimingStatusEnumeration timingStatus;

        /**
         * Gets the value of the timingStatus property.
         * 
         * @return
         *     possible object is
         *     {@link TimingStatusEnumeration }
         *     
         */
        public TimingStatusEnumeration getTimingStatus() {
            return timingStatus;
        }

        /**
         * Sets the value of the timingStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link TimingStatusEnumeration }
         *     
         */
        public void setTimingStatus(TimingStatusEnumeration value) {
            this.timingStatus = value;
        }

    }

}
