//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for Type of Bus Stop. Some stop types have required subelements.
 * 
 * <p>Java class for BusStopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusStopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BusStopType" type="{http://www.naptan.org.uk/}BusStopTypeEnumeration"/>
 *         &lt;element name="TimingStatus" type="{http://www.naptan.org.uk/}TimingStatusEnumeration"/>
 *         &lt;group ref="{http://www.naptan.org.uk/}BusStopClassificationGroup"/>
 *         &lt;element name="AnnotatedCoachRef" type="{http://www.naptan.org.uk/}AnnotatedCoachRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusStopClassificationStructure", propOrder = {
    "busStopType",
    "timingStatus",
    "markedPoint",
    "unmarkedPoint",
    "hailAndRideSection",
    "flexibleZone",
    "annotatedCoachRef"
})
public class BusStopClassificationStructure {

    @XmlElement(name = "BusStopType", required = true)
    protected BusStopTypeEnumeration busStopType;
    @XmlElement(name = "TimingStatus", required = true)
    protected TimingStatusEnumeration timingStatus;
    @XmlElement(name = "MarkedPoint")
    protected MarkedPointStructure markedPoint;
    @XmlElement(name = "UnmarkedPoint")
    protected UnmarkedPointStructure unmarkedPoint;
    @XmlElement(name = "HailAndRideSection")
    protected HailAndRideSectionStructure hailAndRideSection;
    @XmlElement(name = "FlexibleZone")
    protected FlexibleZoneStructure flexibleZone;
    @XmlElement(name = "AnnotatedCoachRef")
    protected List<AnnotatedCoachRefStructure> annotatedCoachRef;

    /**
     * Gets the value of the busStopType property.
     * 
     * @return
     *     possible object is
     *     {@link BusStopTypeEnumeration }
     *     
     */
    public BusStopTypeEnumeration getBusStopType() {
        return busStopType;
    }

    /**
     * Sets the value of the busStopType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusStopTypeEnumeration }
     *     
     */
    public void setBusStopType(BusStopTypeEnumeration value) {
        this.busStopType = value;
    }

    /**
     * Gets the value of the timingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TimingStatusEnumeration }
     *     
     */
    public TimingStatusEnumeration getTimingStatus() {
        return timingStatus;
    }

    /**
     * Sets the value of the timingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimingStatusEnumeration }
     *     
     */
    public void setTimingStatus(TimingStatusEnumeration value) {
        this.timingStatus = value;
    }

    /**
     * Gets the value of the markedPoint property.
     * 
     * @return
     *     possible object is
     *     {@link MarkedPointStructure }
     *     
     */
    public MarkedPointStructure getMarkedPoint() {
        return markedPoint;
    }

    /**
     * Sets the value of the markedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkedPointStructure }
     *     
     */
    public void setMarkedPoint(MarkedPointStructure value) {
        this.markedPoint = value;
    }

    /**
     * Gets the value of the unmarkedPoint property.
     * 
     * @return
     *     possible object is
     *     {@link UnmarkedPointStructure }
     *     
     */
    public UnmarkedPointStructure getUnmarkedPoint() {
        return unmarkedPoint;
    }

    /**
     * Sets the value of the unmarkedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnmarkedPointStructure }
     *     
     */
    public void setUnmarkedPoint(UnmarkedPointStructure value) {
        this.unmarkedPoint = value;
    }

    /**
     * Gets the value of the hailAndRideSection property.
     * 
     * @return
     *     possible object is
     *     {@link HailAndRideSectionStructure }
     *     
     */
    public HailAndRideSectionStructure getHailAndRideSection() {
        return hailAndRideSection;
    }

    /**
     * Sets the value of the hailAndRideSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HailAndRideSectionStructure }
     *     
     */
    public void setHailAndRideSection(HailAndRideSectionStructure value) {
        this.hailAndRideSection = value;
    }

    /**
     * Gets the value of the flexibleZone property.
     * 
     * @return
     *     possible object is
     *     {@link FlexibleZoneStructure }
     *     
     */
    public FlexibleZoneStructure getFlexibleZone() {
        return flexibleZone;
    }

    /**
     * Sets the value of the flexibleZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlexibleZoneStructure }
     *     
     */
    public void setFlexibleZone(FlexibleZoneStructure value) {
        this.flexibleZone = value;
    }

    /**
     * Gets the value of the annotatedCoachRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotatedCoachRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotatedCoachRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotatedCoachRefStructure }
     * 
     * 
     */
    public List<AnnotatedCoachRefStructure> getAnnotatedCoachRef() {
        if (annotatedCoachRef == null) {
            annotatedCoachRef = new ArrayList<AnnotatedCoachRefStructure>();
        }
        return this.annotatedCoachRef;
    }

}
