//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for Type of Taxi stop. 
 * 
 * <p>Java class for CarStopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarStopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SetDownPickUpArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarStopClassificationStructure", propOrder = {
    "setDownPickUpArea"
})
public class CarStopClassificationStructure {

    @XmlElement(name = "SetDownPickUpArea", required = true)
    protected String setDownPickUpArea;

    /**
     * Gets the value of the setDownPickUpArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetDownPickUpArea() {
        return setDownPickUpArea;
    }

    /**
     * Sets the value of the setDownPickUpArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetDownPickUpArea(String value) {
        this.setDownPickUpArea = value;
    }

}
