//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContributorClassificationEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContributorClassificationEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CommunityMember"/>
 *     &lt;enumeration value="ProfessionalOrganisation"/>
 *     &lt;enumeration value="LocalAuthority"/>
 *     &lt;enumeration value="ProfessionalOrganisationForLocalAuthority"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContributorClassificationEnumeration")
@XmlEnum
public enum ContributorClassificationEnumeration {


    /**
     * Contributor is a private individual 
     * 
     */
    @XmlEnumValue("CommunityMember")
    COMMUNITY_MEMBER("CommunityMember"),

    /**
     * Contributor is a professional Organisation
     * 
     */
    @XmlEnumValue("ProfessionalOrganisation")
    PROFESSIONAL_ORGANISATION("ProfessionalOrganisation"),

    /**
     * Contributor is a local authority.
     * 
     */
    @XmlEnumValue("LocalAuthority")
    LOCAL_AUTHORITY("LocalAuthority"),

    /**
     * Contributor is a professional Organisation acting on behalf of a Local Authority.
     * 
     */
    @XmlEnumValue("ProfessionalOrganisationForLocalAuthority")
    PROFESSIONAL_ORGANISATION_FOR_LOCAL_AUTHORITY("ProfessionalOrganisationForLocalAuthority");
    private final String value;

    ContributorClassificationEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContributorClassificationEnumeration fromValue(String v) {
        for (ContributorClassificationEnumeration c: ContributorClassificationEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
