//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContributorRoleEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContributorRoleEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Aggregate"/>
 *     &lt;enumeration value="Distribute"/>
 *     &lt;enumeration value="Supply"/>
 *     &lt;enumeration value="Verifiy"/>
 *     &lt;enumeration value="Own"/>
 *     &lt;enumeration value="Update"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContributorRoleEnumeration")
@XmlEnum
public enum ContributorRoleEnumeration {


    /**
     * Contributor is a local authority.
     * 
     */
    @XmlEnumValue("Aggregate")
    AGGREGATE("Aggregate"),

    /**
     * Contributor is a professional Organisation acting on behalf of a Local Authority.
     * 
     */
    @XmlEnumValue("Distribute")
    DISTRIBUTE("Distribute"),

    /**
     * Contributor is a private individual 
     * 
     */
    @XmlEnumValue("Supply")
    SUPPLY("Supply"),

    /**
     * Contributor is a professional Organisation
     * 
     */
    @XmlEnumValue("Verifiy")
    VERIFIY("Verifiy"),
    @XmlEnumValue("Own")
    OWN("Own"),
    @XmlEnumValue("Update")
    UPDATE("Update");
    private final String value;

    ContributorRoleEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContributorRoleEnumeration fromValue(String v) {
        for (ContributorRoleEnumeration c: ContributorRoleEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
