//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a named of contributors.
 * 
 * <p>Java class for ContributorStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContributorStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}OrganisationStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.naptan.org.uk/}ContributorGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContributorStructure", propOrder = {
    "policyStatus",
    "contributorClassification",
    "dataRights"
})
@XmlSeeAlso({
    Contributor.class
})
public class ContributorStructure
    extends OrganisationStructure
{

    @XmlElement(name = "PolicyStatus", defaultValue = "SubjectToFreedomOfInformation")
    protected PolicyStatusEnumeration policyStatus;
    @XmlElement(name = "ContributorClassification")
    protected ContributorClassificationEnumeration contributorClassification;
    @XmlElement(name = "DataRights")
    protected DataRightsStructure dataRights;

    /**
     * Gets the value of the policyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyStatusEnumeration }
     *     
     */
    public PolicyStatusEnumeration getPolicyStatus() {
        return policyStatus;
    }

    /**
     * Sets the value of the policyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyStatusEnumeration }
     *     
     */
    public void setPolicyStatus(PolicyStatusEnumeration value) {
        this.policyStatus = value;
    }

    /**
     * Gets the value of the contributorClassification property.
     * 
     * @return
     *     possible object is
     *     {@link ContributorClassificationEnumeration }
     *     
     */
    public ContributorClassificationEnumeration getContributorClassification() {
        return contributorClassification;
    }

    /**
     * Sets the value of the contributorClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContributorClassificationEnumeration }
     *     
     */
    public void setContributorClassification(ContributorClassificationEnumeration value) {
        this.contributorClassification = value;
    }

    /**
     * Gets the value of the dataRights property.
     * 
     * @return
     *     possible object is
     *     {@link DataRightsStructure }
     *     
     */
    public DataRightsStructure getDataRights() {
        return dataRights;
    }

    /**
     * Sets the value of the dataRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRightsStructure }
     *     
     */
    public void setDataRights(DataRightsStructure value) {
        this.dataRights = value;
    }

}
