//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for recording the data rights of an element.
 * 
 * <p>Java class for DataRightStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataRightStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}VersionedChildStructure">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.naptan.org.uk/}DataRightGroup"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataRightStructure", propOrder = {
    "termsOfUse",
    "copyright",
    "dataPolicy",
    "verificationStatus"
})
@XmlSeeAlso({
    DataRight.class
})
public class DataRightStructure
    extends VersionedChildStructure
{

    @XmlElement(name = "TermsOfUse")
    protected DataRightStructure.TermsOfUse termsOfUse;
    @XmlElement(name = "Copyright")
    protected DataRightStructure.Copyright copyright;
    @XmlElement(name = "DataPolicy")
    protected DataRightStructure.DataPolicy dataPolicy;
    @XmlElement(name = "VerificationStatus")
    protected VerificationStatusEnumeration verificationStatus;

    /**
     * Gets the value of the termsOfUse property.
     * 
     * @return
     *     possible object is
     *     {@link DataRightStructure.TermsOfUse }
     *     
     */
    public DataRightStructure.TermsOfUse getTermsOfUse() {
        return termsOfUse;
    }

    /**
     * Sets the value of the termsOfUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRightStructure.TermsOfUse }
     *     
     */
    public void setTermsOfUse(DataRightStructure.TermsOfUse value) {
        this.termsOfUse = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link DataRightStructure.Copyright }
     *     
     */
    public DataRightStructure.Copyright getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRightStructure.Copyright }
     *     
     */
    public void setCopyright(DataRightStructure.Copyright value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the dataPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link DataRightStructure.DataPolicy }
     *     
     */
    public DataRightStructure.DataPolicy getDataPolicy() {
        return dataPolicy;
    }

    /**
     * Sets the value of the dataPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRightStructure.DataPolicy }
     *     
     */
    public void setDataPolicy(DataRightStructure.DataPolicy value) {
        this.dataPolicy = value;
    }

    /**
     * Gets the value of the verificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationStatusEnumeration }
     *     
     */
    public VerificationStatusEnumeration getVerificationStatus() {
        return verificationStatus;
    }

    /**
     * Sets the value of the verificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationStatusEnumeration }
     *     
     */
    public void setVerificationStatus(VerificationStatusEnumeration value) {
        this.verificationStatus = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CopyrightUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="CopyrightStatement" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "copyrightUrl",
        "copyrightStatement"
    })
    public static class Copyright {

        @XmlElement(name = "CopyrightUrl")
        @XmlSchemaType(name = "anyURI")
        protected String copyrightUrl;
        @XmlElement(name = "CopyrightStatement")
        protected NaturalLanguageStringStructure copyrightStatement;

        /**
         * Gets the value of the copyrightUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCopyrightUrl() {
            return copyrightUrl;
        }

        /**
         * Sets the value of the copyrightUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCopyrightUrl(String value) {
            this.copyrightUrl = value;
        }

        /**
         * Gets the value of the copyrightStatement property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public NaturalLanguageStringStructure getCopyrightStatement() {
            return copyrightStatement;
        }

        /**
         * Sets the value of the copyrightStatement property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public void setCopyrightStatement(NaturalLanguageStringStructure value) {
            this.copyrightStatement = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PolicyStatus" type="{http://www.naptan.org.uk/}PolicyStatusEnumeration" minOccurs="0"/>
     *         &lt;element name="PolicyUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="PolicyJustification" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "policyStatus",
        "policyUrl",
        "policyJustification"
    })
    public static class DataPolicy {

        @XmlElement(name = "PolicyStatus", defaultValue = "ExemptFromFreedomOfInformation")
        protected PolicyStatusEnumeration policyStatus;
        @XmlElement(name = "PolicyUrl")
        @XmlSchemaType(name = "anyURI")
        protected String policyUrl;
        @XmlElement(name = "PolicyJustification")
        protected NaturalLanguageStringStructure policyJustification;

        /**
         * Gets the value of the policyStatus property.
         * 
         * @return
         *     possible object is
         *     {@link PolicyStatusEnumeration }
         *     
         */
        public PolicyStatusEnumeration getPolicyStatus() {
            return policyStatus;
        }

        /**
         * Sets the value of the policyStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link PolicyStatusEnumeration }
         *     
         */
        public void setPolicyStatus(PolicyStatusEnumeration value) {
            this.policyStatus = value;
        }

        /**
         * Gets the value of the policyUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPolicyUrl() {
            return policyUrl;
        }

        /**
         * Sets the value of the policyUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPolicyUrl(String value) {
            this.policyUrl = value;
        }

        /**
         * Gets the value of the policyJustification property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public NaturalLanguageStringStructure getPolicyJustification() {
            return policyJustification;
        }

        /**
         * Sets the value of the policyJustification property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public void setPolicyJustification(NaturalLanguageStringStructure value) {
            this.policyJustification = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AllowedUse" type="{http://www.naptan.org.uk/}AllowedUseEnumeration" minOccurs="0"/>
     *         &lt;element name="TermsOfUseUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="TermsAndConditions" type="{http://www.naptan.org.uk/}NaturalLanguageStringStructure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "allowedUse",
        "termsOfUseUrl",
        "termsAndConditions"
    })
    public static class TermsOfUse {

        @XmlElement(name = "AllowedUse")
        protected AllowedUseEnumeration allowedUse;
        @XmlElement(name = "TermsOfUseUrl")
        @XmlSchemaType(name = "anyURI")
        protected String termsOfUseUrl;
        @XmlElement(name = "TermsAndConditions")
        protected NaturalLanguageStringStructure termsAndConditions;

        /**
         * Gets the value of the allowedUse property.
         * 
         * @return
         *     possible object is
         *     {@link AllowedUseEnumeration }
         *     
         */
        public AllowedUseEnumeration getAllowedUse() {
            return allowedUse;
        }

        /**
         * Sets the value of the allowedUse property.
         * 
         * @param value
         *     allowed object is
         *     {@link AllowedUseEnumeration }
         *     
         */
        public void setAllowedUse(AllowedUseEnumeration value) {
            this.allowedUse = value;
        }

        /**
         * Gets the value of the termsOfUseUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermsOfUseUrl() {
            return termsOfUseUrl;
        }

        /**
         * Sets the value of the termsOfUseUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermsOfUseUrl(String value) {
            this.termsOfUseUrl = value;
        }

        /**
         * Gets the value of the termsAndConditions property.
         * 
         * @return
         *     possible object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public NaturalLanguageStringStructure getTermsAndConditions() {
            return termsAndConditions;
        }

        /**
         * Sets the value of the termsAndConditions property.
         * 
         * @param value
         *     allowed object is
         *     {@link NaturalLanguageStringStructure }
         *     
         */
        public void setTermsAndConditions(NaturalLanguageStringStructure value) {
            this.termsAndConditions = value;
        }

    }

}
