//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for a geographical zone of operation within which a flexible service operates.
 * 
 * <p>Java class for FlexibleZoneStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlexibleZoneStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}BusStopTypeStructure">
 *       &lt;sequence>
 *         &lt;element name="Location" type="{http://www.naptan.org.uk/}LocationStructure" maxOccurs="unbounded" minOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlexibleZoneStructure", propOrder = {
    "location"
})
public class FlexibleZoneStructure
    extends BusStopTypeStructure
{

    @XmlElement(name = "Location", required = true)
    protected List<LocationStructure> location;

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationStructure }
     * 
     * 
     */
    public List<LocationStructure> getLocation() {
        if (location == null) {
            location = new ArrayList<LocationStructure>();
        }
        return this.location;
    }

}
