//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Definition of the hail and ride section.
 * 
 * <p>Java class for HailAndRideSectionStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HailAndRideSectionStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}BusStopTypeStructure">
 *       &lt;sequence>
 *         &lt;element name="StartPoint" type="{http://www.naptan.org.uk/}LocationStructure"/>
 *         &lt;element name="EndPoint" type="{http://www.naptan.org.uk/}LocationStructure"/>
 *         &lt;element name="Bearing" type="{http://www.naptan.org.uk/}BearingStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HailAndRideSectionStructure", propOrder = {
    "startPoint",
    "endPoint",
    "bearing"
})
public class HailAndRideSectionStructure
    extends BusStopTypeStructure
{

    @XmlElement(name = "StartPoint", required = true)
    protected LocationStructure startPoint;
    @XmlElement(name = "EndPoint", required = true)
    protected LocationStructure endPoint;
    @XmlElement(name = "Bearing")
    protected BearingStructure bearing;

    /**
     * Gets the value of the startPoint property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getStartPoint() {
        return startPoint;
    }

    /**
     * Sets the value of the startPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setStartPoint(LocationStructure value) {
        this.startPoint = value;
    }

    /**
     * Gets the value of the endPoint property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getEndPoint() {
        return endPoint;
    }

    /**
     * Sets the value of the endPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setEndPoint(LocationStructure value) {
        this.endPoint = value;
    }

    /**
     * Gets the value of the bearing property.
     * 
     * @return
     *     possible object is
     *     {@link BearingStructure }
     *     
     */
    public BearingStructure getBearing() {
        return bearing;
    }

    /**
     * Sets the value of the bearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BearingStructure }
     *     
     */
    public void setBearing(BearingStructure value) {
        this.bearing = value;
    }

}
