//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyStatusEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PolicyStatusEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SubjectToFreedomOfInformation"/>
 *     &lt;enumeration value="ExemptFromFreedomOfInformation"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PolicyStatusEnumeration")
@XmlEnum
public enum PolicyStatusEnumeration {


    /**
     * Holder is Subject to the Freedom Of information Act.
     * 
     */
    @XmlEnumValue("SubjectToFreedomOfInformation")
    SUBJECT_TO_FREEDOM_OF_INFORMATION("SubjectToFreedomOfInformation"),

    /**
     * Holder is not Subject to the Freedom Of information Act.
     * 
     */
    @XmlEnumValue("ExemptFromFreedomOfInformation")
    EXEMPT_FROM_FREEDOM_OF_INFORMATION("ExemptFromFreedomOfInformation"),

    /**
     * Other.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PolicyStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PolicyStatusEnumeration fromValue(String v) {
        for (PolicyStatusEnumeration c: PolicyStatusEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
