//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for Type of Rail Stop
 * 
 * <p>Java class for RailStopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RailStopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Entrance" type="{http://www.naptan.org.uk/}EmptyType"/>
 *           &lt;element name="AccessArea" type="{http://www.naptan.org.uk/}EmptyType"/>
 *           &lt;element name="Platform" type="{http://www.naptan.org.uk/}EmptyType"/>
 *         &lt;/choice>
 *         &lt;element name="AnnotatedRailRef" type="{http://www.naptan.org.uk/}AnnotatedRailRefStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RailStopClassificationStructure", propOrder = {
    "entrance",
    "accessArea",
    "platform",
    "annotatedRailRef"
})
public class RailStopClassificationStructure {

    @XmlElement(name = "Entrance")
    protected String entrance;
    @XmlElement(name = "AccessArea")
    protected String accessArea;
    @XmlElement(name = "Platform")
    protected String platform;
    @XmlElement(name = "AnnotatedRailRef")
    protected List<AnnotatedRailRefStructure> annotatedRailRef;

    /**
     * Gets the value of the entrance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntrance() {
        return entrance;
    }

    /**
     * Sets the value of the entrance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntrance(String value) {
        this.entrance = value;
    }

    /**
     * Gets the value of the accessArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessArea() {
        return accessArea;
    }

    /**
     * Sets the value of the accessArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessArea(String value) {
        this.accessArea = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the annotatedRailRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotatedRailRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotatedRailRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotatedRailRefStructure }
     * 
     * 
     */
    public List<AnnotatedRailRefStructure> getAnnotatedRailRef() {
        if (annotatedRailRef == null) {
            annotatedRailRef = new ArrayList<AnnotatedRailRefStructure>();
        }
        return this.annotatedRailRef;
    }

}
