//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StopUseEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StopUseEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="school"/>
 *     &lt;enumeration value="military"/>
 *     &lt;enumeration value="company"/>
 *     &lt;enumeration value="government"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StopUseEnumeration")
@XmlEnum
public enum StopUseEnumeration {

    @XmlEnumValue("school")
    SCHOOL("school"),
    @XmlEnumValue("military")
    MILITARY("military"),
    @XmlEnumValue("company")
    COMPANY("company"),
    @XmlEnumValue("government")
    GOVERNMENT("government"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    StopUseEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StopUseEnumeration fromValue(String v) {
        for (StopUseEnumeration c: StopUseEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
