//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Data type for Type of stop. Some stop types have required subelements.
 * 
 * <p>Java class for StopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StopType" type="{http://www.naptan.org.uk/}StopTypeEnumeration"/>
 *         &lt;choice>
 *           &lt;element name="OnStreet">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element name="Bus" type="{http://www.naptan.org.uk/}BusStopClassificationStructure"/>
 *                     &lt;element name="Taxi">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;choice>
 *                               &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                               &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
 *                             &lt;/choice>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="Car" type="{http://www.naptan.org.uk/}CarStopClassificationStructure"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="OffStreet">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element name="Air" type="{http://www.naptan.org.uk/}AirStopClassificationStructure"/>
 *                     &lt;element name="Ferry" type="{http://www.naptan.org.uk/}FerryStopClassificationStructure"/>
 *                     &lt;element name="Rail" type="{http://www.naptan.org.uk/}RailStopClassificationStructure"/>
 *                     &lt;element name="Metro" type="{http://www.naptan.org.uk/}MetroStopClassificationStructure"/>
 *                     &lt;element name="BusAndCoach" type="{http://www.naptan.org.uk/}BusAndCoachStopClassificationStructure"/>
 *                     &lt;element name="Telecabine" type="{http://www.naptan.org.uk/}LiftCableCarStopClassificationStructure"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopClassificationStructure", propOrder = {
    "stopType",
    "onStreet",
    "offStreet"
})
public class StopClassificationStructure {

    @XmlElement(name = "StopType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String stopType;
    @XmlElement(name = "OnStreet")
    protected StopClassificationStructure.OnStreet onStreet;
    @XmlElement(name = "OffStreet")
    protected StopClassificationStructure.OffStreet offStreet;

    /**
     * Gets the value of the stopType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopType() {
        return stopType;
    }

    /**
     * Sets the value of the stopType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopType(String value) {
        this.stopType = value;
    }

    /**
     * Gets the value of the onStreet property.
     * 
     * @return
     *     possible object is
     *     {@link StopClassificationStructure.OnStreet }
     *     
     */
    public StopClassificationStructure.OnStreet getOnStreet() {
        return onStreet;
    }

    /**
     * Sets the value of the onStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopClassificationStructure.OnStreet }
     *     
     */
    public void setOnStreet(StopClassificationStructure.OnStreet value) {
        this.onStreet = value;
    }

    /**
     * Gets the value of the offStreet property.
     * 
     * @return
     *     possible object is
     *     {@link StopClassificationStructure.OffStreet }
     *     
     */
    public StopClassificationStructure.OffStreet getOffStreet() {
        return offStreet;
    }

    /**
     * Sets the value of the offStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopClassificationStructure.OffStreet }
     *     
     */
    public void setOffStreet(StopClassificationStructure.OffStreet value) {
        this.offStreet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Air" type="{http://www.naptan.org.uk/}AirStopClassificationStructure"/>
     *         &lt;element name="Ferry" type="{http://www.naptan.org.uk/}FerryStopClassificationStructure"/>
     *         &lt;element name="Rail" type="{http://www.naptan.org.uk/}RailStopClassificationStructure"/>
     *         &lt;element name="Metro" type="{http://www.naptan.org.uk/}MetroStopClassificationStructure"/>
     *         &lt;element name="BusAndCoach" type="{http://www.naptan.org.uk/}BusAndCoachStopClassificationStructure"/>
     *         &lt;element name="Telecabine" type="{http://www.naptan.org.uk/}LiftCableCarStopClassificationStructure"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "air",
        "ferry",
        "rail",
        "metro",
        "busAndCoach",
        "telecabine"
    })
    public static class OffStreet {

        @XmlElement(name = "Air")
        protected AirStopClassificationStructure air;
        @XmlElement(name = "Ferry")
        protected FerryStopClassificationStructure ferry;
        @XmlElement(name = "Rail")
        protected RailStopClassificationStructure rail;
        @XmlElement(name = "Metro")
        protected MetroStopClassificationStructure metro;
        @XmlElement(name = "BusAndCoach")
        protected BusAndCoachStopClassificationStructure busAndCoach;
        @XmlElement(name = "Telecabine")
        protected LiftCableCarStopClassificationStructure telecabine;

        /**
         * Gets the value of the air property.
         * 
         * @return
         *     possible object is
         *     {@link AirStopClassificationStructure }
         *     
         */
        public AirStopClassificationStructure getAir() {
            return air;
        }

        /**
         * Sets the value of the air property.
         * 
         * @param value
         *     allowed object is
         *     {@link AirStopClassificationStructure }
         *     
         */
        public void setAir(AirStopClassificationStructure value) {
            this.air = value;
        }

        /**
         * Gets the value of the ferry property.
         * 
         * @return
         *     possible object is
         *     {@link FerryStopClassificationStructure }
         *     
         */
        public FerryStopClassificationStructure getFerry() {
            return ferry;
        }

        /**
         * Sets the value of the ferry property.
         * 
         * @param value
         *     allowed object is
         *     {@link FerryStopClassificationStructure }
         *     
         */
        public void setFerry(FerryStopClassificationStructure value) {
            this.ferry = value;
        }

        /**
         * Gets the value of the rail property.
         * 
         * @return
         *     possible object is
         *     {@link RailStopClassificationStructure }
         *     
         */
        public RailStopClassificationStructure getRail() {
            return rail;
        }

        /**
         * Sets the value of the rail property.
         * 
         * @param value
         *     allowed object is
         *     {@link RailStopClassificationStructure }
         *     
         */
        public void setRail(RailStopClassificationStructure value) {
            this.rail = value;
        }

        /**
         * Gets the value of the metro property.
         * 
         * @return
         *     possible object is
         *     {@link MetroStopClassificationStructure }
         *     
         */
        public MetroStopClassificationStructure getMetro() {
            return metro;
        }

        /**
         * Sets the value of the metro property.
         * 
         * @param value
         *     allowed object is
         *     {@link MetroStopClassificationStructure }
         *     
         */
        public void setMetro(MetroStopClassificationStructure value) {
            this.metro = value;
        }

        /**
         * Gets the value of the busAndCoach property.
         * 
         * @return
         *     possible object is
         *     {@link BusAndCoachStopClassificationStructure }
         *     
         */
        public BusAndCoachStopClassificationStructure getBusAndCoach() {
            return busAndCoach;
        }

        /**
         * Sets the value of the busAndCoach property.
         * 
         * @param value
         *     allowed object is
         *     {@link BusAndCoachStopClassificationStructure }
         *     
         */
        public void setBusAndCoach(BusAndCoachStopClassificationStructure value) {
            this.busAndCoach = value;
        }

        /**
         * Gets the value of the telecabine property.
         * 
         * @return
         *     possible object is
         *     {@link LiftCableCarStopClassificationStructure }
         *     
         */
        public LiftCableCarStopClassificationStructure getTelecabine() {
            return telecabine;
        }

        /**
         * Sets the value of the telecabine property.
         * 
         * @param value
         *     allowed object is
         *     {@link LiftCableCarStopClassificationStructure }
         *     
         */
        public void setTelecabine(LiftCableCarStopClassificationStructure value) {
            this.telecabine = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Bus" type="{http://www.naptan.org.uk/}BusStopClassificationStructure"/>
     *         &lt;element name="Taxi">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                   &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Car" type="{http://www.naptan.org.uk/}CarStopClassificationStructure"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bus",
        "taxi",
        "car"
    })
    public static class OnStreet {

        @XmlElement(name = "Bus")
        protected BusStopClassificationStructure bus;
        @XmlElement(name = "Taxi")
        protected StopClassificationStructure.OnStreet.Taxi taxi;
        @XmlElement(name = "Car")
        protected CarStopClassificationStructure car;

        /**
         * Gets the value of the bus property.
         * 
         * @return
         *     possible object is
         *     {@link BusStopClassificationStructure }
         *     
         */
        public BusStopClassificationStructure getBus() {
            return bus;
        }

        /**
         * Sets the value of the bus property.
         * 
         * @param value
         *     allowed object is
         *     {@link BusStopClassificationStructure }
         *     
         */
        public void setBus(BusStopClassificationStructure value) {
            this.bus = value;
        }

        /**
         * Gets the value of the taxi property.
         * 
         * @return
         *     possible object is
         *     {@link StopClassificationStructure.OnStreet.Taxi }
         *     
         */
        public StopClassificationStructure.OnStreet.Taxi getTaxi() {
            return taxi;
        }

        /**
         * Sets the value of the taxi property.
         * 
         * @param value
         *     allowed object is
         *     {@link StopClassificationStructure.OnStreet.Taxi }
         *     
         */
        public void setTaxi(StopClassificationStructure.OnStreet.Taxi value) {
            this.taxi = value;
        }

        /**
         * Gets the value of the car property.
         * 
         * @return
         *     possible object is
         *     {@link CarStopClassificationStructure }
         *     
         */
        public CarStopClassificationStructure getCar() {
            return car;
        }

        /**
         * Sets the value of the car property.
         * 
         * @param value
         *     allowed object is
         *     {@link CarStopClassificationStructure }
         *     
         */
        public void setCar(CarStopClassificationStructure value) {
            this.car = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
         *         &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "taxiRank",
            "sharedTaxiRank"
        })
        public static class Taxi {

            @XmlElement(name = "TaxiRank")
            protected String taxiRank;
            @XmlElement(name = "SharedTaxiRank")
            protected String sharedTaxiRank;

            /**
             * Gets the value of the taxiRank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxiRank() {
                return taxiRank;
            }

            /**
             * Sets the value of the taxiRank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxiRank(String value) {
                this.taxiRank = value;
            }

            /**
             * Gets the value of the sharedTaxiRank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSharedTaxiRank() {
                return sharedTaxiRank;
            }

            /**
             * Sets the value of the sharedTaxiRank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSharedTaxiRank(String value) {
                this.sharedTaxiRank = value;
            }

        }

    }

}
