//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A group or area of related stops.
 * 
 * <p>Java class for StopAreaStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopAreaStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}VersionedObjectTimestampedStructure">
 *       &lt;sequence>
 *         &lt;element name="StopAreaCode" type="{http://www.naptan.org.uk/}StopAreaCodeType"/>
 *         &lt;element name="PrivateCode" type="{http://www.naptan.org.uk/}PrivateCodeType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.naptan.org.uk/}NaturalLanguagePlaceNameStructure"/>
 *         &lt;element name="ParentStopAreaRef" type="{http://www.naptan.org.uk/}StopAreaVersionedRefStructure" minOccurs="0"/>
 *         &lt;element name="AdministrativeAreaRef" type="{http://www.naptan.org.uk/}AdministrativeAreaRefStructure"/>
 *         &lt;element name="StopAreaType" type="{http://www.naptan.org.uk/}StopAreaTypeEnumeration"/>
 *         &lt;element name="Location" type="{http://www.naptan.org.uk/}LocationStructure"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopAreaStructure", propOrder = {
    "stopAreaCode",
    "privateCode",
    "name",
    "parentStopAreaRef",
    "administrativeAreaRef",
    "stopAreaType",
    "location"
})
@XmlSeeAlso({
    StopArea.class
})
public class StopAreaStructure
    extends VersionedObjectTimestampedStructure
{

    @XmlElement(name = "StopAreaCode", required = true)
    protected String stopAreaCode;
    @XmlElement(name = "PrivateCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String privateCode;
    @XmlElement(name = "Name", required = true)
    protected NaturalLanguagePlaceNameStructure name;
    @XmlElement(name = "ParentStopAreaRef")
    protected StopAreaVersionedRefStructure parentStopAreaRef;
    @XmlElement(name = "AdministrativeAreaRef", required = true)
    protected AdministrativeAreaRefStructure administrativeAreaRef;
    @XmlElement(name = "StopAreaType", required = true)
    protected StopAreaTypeEnumeration stopAreaType;
    @XmlElement(name = "Location", required = true)
    protected LocationStructure location;

    /**
     * Gets the value of the stopAreaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopAreaCode() {
        return stopAreaCode;
    }

    /**
     * Sets the value of the stopAreaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopAreaCode(String value) {
        this.stopAreaCode = value;
    }

    /**
     * Gets the value of the privateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateCode() {
        return privateCode;
    }

    /**
     * Sets the value of the privateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateCode(String value) {
        this.privateCode = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public NaturalLanguagePlaceNameStructure getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePlaceNameStructure }
     *     
     */
    public void setName(NaturalLanguagePlaceNameStructure value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentStopAreaRef property.
     * 
     * @return
     *     possible object is
     *     {@link StopAreaVersionedRefStructure }
     *     
     */
    public StopAreaVersionedRefStructure getParentStopAreaRef() {
        return parentStopAreaRef;
    }

    /**
     * Sets the value of the parentStopAreaRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopAreaVersionedRefStructure }
     *     
     */
    public void setParentStopAreaRef(StopAreaVersionedRefStructure value) {
        this.parentStopAreaRef = value;
    }

    /**
     * Gets the value of the administrativeAreaRef property.
     * 
     * @return
     *     possible object is
     *     {@link AdministrativeAreaRefStructure }
     *     
     */
    public AdministrativeAreaRefStructure getAdministrativeAreaRef() {
        return administrativeAreaRef;
    }

    /**
     * Sets the value of the administrativeAreaRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdministrativeAreaRefStructure }
     *     
     */
    public void setAdministrativeAreaRef(AdministrativeAreaRefStructure value) {
        this.administrativeAreaRef = value;
    }

    /**
     * Gets the value of the stopAreaType property.
     * 
     * @return
     *     possible object is
     *     {@link StopAreaTypeEnumeration }
     *     
     */
    public StopAreaTypeEnumeration getStopAreaType() {
        return stopAreaType;
    }

    /**
     * Sets the value of the stopAreaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StopAreaTypeEnumeration }
     *     
     */
    public void setStopAreaType(StopAreaTypeEnumeration value) {
        this.stopAreaType = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStructure }
     *     
     */
    public LocationStructure getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStructure }
     *     
     */
    public void setLocation(LocationStructure value) {
        this.location = value;
    }

}
