//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of one or more stops.
 * 
 * <p>Java class for StopPointsStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopPointsStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.naptan.org.uk/}DeltaListStructure">
 *       &lt;sequence>
 *         &lt;element name="StopPoint" type="{http://www.naptan.org.uk/}StopPointStructure" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopPointsStructure", propOrder = {
    "stopPoint"
})
public class StopPointsStructure
    extends DeltaListStructure
{

    @XmlElement(name = "StopPoint", required = true)
    protected List<StopPointStructure> stopPoint;

    /**
     * Gets the value of the stopPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stopPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStopPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StopPointStructure }
     * 
     * 
     */
    public List<StopPointStructure> getStopPoint() {
        if (stopPoint == null) {
            stopPoint = new ArrayList<StopPointStructure>();
        }
        return this.stopPoint;
    }

}
