//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data type for Type of Taxi stop. 
 * 
 * <p>Java class for TaxiStopClassificationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaxiStopClassificationStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
 *         &lt;element name="SharedTaxiRank" type="{http://www.naptan.org.uk/}EmptyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxiStopClassificationStructure", propOrder = {
    "taxiRank",
    "sharedTaxiRank"
})
public class TaxiStopClassificationStructure {

    @XmlElement(name = "TaxiRank", required = true)
    protected String taxiRank;
    @XmlElement(name = "SharedTaxiRank", required = true)
    protected String sharedTaxiRank;

    /**
     * Gets the value of the taxiRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxiRank() {
        return taxiRank;
    }

    /**
     * Sets the value of the taxiRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxiRank(String value) {
        this.taxiRank = value;
    }

    /**
     * Gets the value of the sharedTaxiRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSharedTaxiRank() {
        return sharedTaxiRank;
    }

    /**
     * Sets the value of the sharedTaxiRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSharedTaxiRank(String value) {
        this.sharedTaxiRank = value;
    }

}
