//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerificationStatusEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VerificationStatusEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Unverified"/>
 *     &lt;enumeration value="CommunityVerified"/>
 *     &lt;enumeration value="ProfessionallyVerified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VerificationStatusEnumeration")
@XmlEnum
public enum VerificationStatusEnumeration {


    /**
     * Data has not been verified.
     * 
     */
    @XmlEnumValue("Unverified")
    UNVERIFIED("Unverified"),

    /**
     * Data has   been verified by a community organisation.
     * 
     */
    @XmlEnumValue("CommunityVerified")
    COMMUNITY_VERIFIED("CommunityVerified"),

    /**
     * Data has   been verified by a professional organisation.
     * 
     */
    @XmlEnumValue("ProfessionallyVerified")
    PROFESSIONALLY_VERIFIED("ProfessionallyVerified");
    private final String value;

    VerificationStatusEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VerificationStatusEnumeration fromValue(String v) {
        for (VerificationStatusEnumeration c: VerificationStatusEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
