//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.org.naptan;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Type for a  versioned object with change tracking attributes, Mandatiory creation date
 * 
 * <p>Java class for VersionedObjectTimestampedStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionedObjectTimestampedStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.naptan.org.uk/}VersionedObjectStructure">
 *       &lt;attribute name="id" type="{http://www.naptan.org.uk/}IdType" />
 *       &lt;attribute name="CreationDateTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="ModificationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="Modification" type="{http://www.naptan.org.uk/}ModificationEnumeration" default="new" />
 *       &lt;attribute name="RevisionNumber" type="{http://www.naptan.org.uk/}RevisionNumberType" />
 *       &lt;attribute name="Status" type="{http://www.naptan.org.uk/}StatusEnumeration" default="active" />
 *       &lt;attribute name="BaselineVersion" type="{http://www.naptan.org.uk/}RevisionNumberType" />
 *       &lt;attribute name="DataRightRef" type="{http://www.naptan.org.uk/}DataRightIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionedObjectTimestampedStructure")
@XmlSeeAlso({
    StopPointStructure.class,
    StopAreaStructure.class
})
public class VersionedObjectTimestampedStructure
    extends VersionedObjectStructure
{


}
