//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.addressandpersonaldetails;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressValidationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressValidationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="not-checked"/>
 *     &lt;enumeration value="PAF-check-failed"/>
 *     &lt;enumeration value="NLPG-check-failed"/>
 *     &lt;enumeration value="PAF-check-valid"/>
 *     &lt;enumeration value="NLPG-check-valid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AddressValidationType")
@XmlEnum
public enum AddressValidationType {

    @XmlEnumValue("not-checked")
    NOT_CHECKED("not-checked"),
    @XmlEnumValue("PAF-check-failed")
    PAF_CHECK_FAILED("PAF-check-failed"),
    @XmlEnumValue("NLPG-check-failed")
    NLPG_CHECK_FAILED("NLPG-check-failed"),
    @XmlEnumValue("PAF-check-valid")
    PAF_CHECK_VALID("PAF-check-valid"),
    @XmlEnumValue("NLPG-check-valid")
    NLPG_CHECK_VALID("NLPG-check-valid");
    private final String value;

    AddressValidationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddressValidationType fromValue(String v) {
        for (AddressValidationType c: AddressValidationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
