//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.addressandpersonaldetails;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import uk.gov.govtalk.people.bs7666.BSaddressStructure;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.govtalk.people.addressandpersonaldetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InternationalAddressStructureInternationalPostCode_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "InternationalPostCode");
    private final static QName _InternationalAddressStructureCountry_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "Country");
    private final static QName _InternationalAddressStructureIntAddressLine_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "IntAddressLine");
    private final static QName _UKAddressStructureA5LineAddress_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "A_5LineAddress");
    private final static QName _UKAddressStructureBS7666Address_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "BS7666Address");
    private final static QName _UKAddressStructureSortCode_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "SortCode");
    private final static QName _UKAddressStructureUniquePropertyReferenceNumber_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "UniquePropertyReferenceNumber");
    private final static QName _UKAddressStructureWalkSort_QNAME = new QName("http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", "WalkSort");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.govtalk.people.addressandpersonaldetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UKPostalAddressStructure }
     * 
     */
    public UKPostalAddressStructure createUKPostalAddressStructure() {
        return new UKPostalAddressStructure();
    }

    /**
     * Create an instance of {@link UKAddressStructure }
     * 
     */
    public UKAddressStructure createUKAddressStructure() {
        return new UKAddressStructure();
    }

    /**
     * Create an instance of {@link InternationalAddressStructure }
     * 
     */
    public InternationalAddressStructure createInternationalAddressStructure() {
        return new InternationalAddressStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "InternationalPostCode", scope = InternationalAddressStructure.class)
    public JAXBElement<String> createInternationalAddressStructureInternationalPostCode(String value) {
        return new JAXBElement<String>(_InternationalAddressStructureInternationalPostCode_QNAME, String.class, InternationalAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "Country", scope = InternationalAddressStructure.class)
    public JAXBElement<String> createInternationalAddressStructureCountry(String value) {
        return new JAXBElement<String>(_InternationalAddressStructureCountry_QNAME, String.class, InternationalAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "IntAddressLine", scope = InternationalAddressStructure.class)
    public JAXBElement<String> createInternationalAddressStructureIntAddressLine(String value) {
        return new JAXBElement<String>(_InternationalAddressStructureIntAddressLine_QNAME, String.class, InternationalAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UKPostalAddressStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "A_5LineAddress", scope = UKAddressStructure.class)
    public JAXBElement<UKPostalAddressStructure> createUKAddressStructureA5LineAddress(UKPostalAddressStructure value) {
        return new JAXBElement<UKPostalAddressStructure>(_UKAddressStructureA5LineAddress_QNAME, UKPostalAddressStructure.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "BS7666Address", scope = UKAddressStructure.class)
    public JAXBElement<BSaddressStructure> createUKAddressStructureBS7666Address(BSaddressStructure value) {
        return new JAXBElement<BSaddressStructure>(_UKAddressStructureBS7666Address_QNAME, BSaddressStructure.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "SortCode", scope = UKAddressStructure.class)
    public JAXBElement<String> createUKAddressStructureSortCode(String value) {
        return new JAXBElement<String>(_UKAddressStructureSortCode_QNAME, String.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "UniquePropertyReferenceNumber", scope = UKAddressStructure.class)
    public JAXBElement<Long> createUKAddressStructureUniquePropertyReferenceNumber(Long value) {
        return new JAXBElement<Long>(_UKAddressStructureUniquePropertyReferenceNumber_QNAME, Long.class, UKAddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/AddressAndPersonalDetails", name = "WalkSort", scope = UKAddressStructure.class)
    public JAXBElement<String> createUKAddressStructureWalkSort(String value) {
        return new JAXBElement<String>(_UKAddressStructureWalkSort_QNAME, String.class, UKAddressStructure.class, value);
    }

}
