//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BasicLandAndPropertyUnitStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicLandAndPropertyUnitStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.govtalk.gov.uk/people/bs7666}UniquePropertyReferenceNumber"/>
 *         &lt;element name="CustodianCode" type="{http://www.govtalk.gov.uk/people/bs7666}CustodianCodeType"/>
 *         &lt;element name="RepresentativePointCode" type="{http://www.govtalk.gov.uk/people/bs7666}RepresentativePointCodeType"/>
 *         &lt;element name="LogicalStatus" type="{http://www.govtalk.gov.uk/people/bs7666}LogicalStatusType"/>
 *         &lt;element name="GridReference" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure"/>
 *         &lt;element name="BLPUentryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="BLPUstartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="BLPUendDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="BLPUlastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LandAndPropertyIdentifier" type="{http://www.govtalk.gov.uk/people/bs7666}LandAndPropertyIdentifierStructure" maxOccurs="unbounded"/>
 *         &lt;element name="Provenance" type="{http://www.govtalk.gov.uk/people/bs7666}ProvenanceStructure" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicLandAndPropertyUnitStructure", propOrder = {
    "uniquePropertyReferenceNumber",
    "custodianCode",
    "representativePointCode",
    "logicalStatus",
    "gridReference",
    "blpUentryDate",
    "blpUstartDate",
    "blpUendDate",
    "blpUlastUpdateDate",
    "landAndPropertyIdentifier",
    "provenance"
})
public class BasicLandAndPropertyUnitStructure {

    @XmlElement(name = "UniquePropertyReferenceNumber")
    protected long uniquePropertyReferenceNumber;
    @XmlElement(name = "CustodianCode")
    protected int custodianCode;
    @XmlElement(name = "RepresentativePointCode", required = true)
    protected BigInteger representativePointCode;
    @XmlElement(name = "LogicalStatus")
    protected int logicalStatus;
    @XmlElement(name = "GridReference", required = true)
    protected CoordinateStructure gridReference;
    @XmlElement(name = "BLPUentryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar blpUentryDate;
    @XmlElement(name = "BLPUstartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar blpUstartDate;
    @XmlElement(name = "BLPUendDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar blpUendDate;
    @XmlElement(name = "BLPUlastUpdateDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar blpUlastUpdateDate;
    @XmlElement(name = "LandAndPropertyIdentifier", required = true)
    protected List<LandAndPropertyIdentifierStructure> landAndPropertyIdentifier;
    @XmlElement(name = "Provenance", required = true)
    protected List<ProvenanceStructure> provenance;

    /**
     * Gets the value of the uniquePropertyReferenceNumber property.
     * 
     */
    public long getUniquePropertyReferenceNumber() {
        return uniquePropertyReferenceNumber;
    }

    /**
     * Sets the value of the uniquePropertyReferenceNumber property.
     * 
     */
    public void setUniquePropertyReferenceNumber(long value) {
        this.uniquePropertyReferenceNumber = value;
    }

    /**
     * Gets the value of the custodianCode property.
     * 
     */
    public int getCustodianCode() {
        return custodianCode;
    }

    /**
     * Sets the value of the custodianCode property.
     * 
     */
    public void setCustodianCode(int value) {
        this.custodianCode = value;
    }

    /**
     * Gets the value of the representativePointCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRepresentativePointCode() {
        return representativePointCode;
    }

    /**
     * Sets the value of the representativePointCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRepresentativePointCode(BigInteger value) {
        this.representativePointCode = value;
    }

    /**
     * Gets the value of the logicalStatus property.
     * 
     */
    public int getLogicalStatus() {
        return logicalStatus;
    }

    /**
     * Sets the value of the logicalStatus property.
     * 
     */
    public void setLogicalStatus(int value) {
        this.logicalStatus = value;
    }

    /**
     * Gets the value of the gridReference property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateStructure }
     *     
     */
    public CoordinateStructure getGridReference() {
        return gridReference;
    }

    /**
     * Sets the value of the gridReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateStructure }
     *     
     */
    public void setGridReference(CoordinateStructure value) {
        this.gridReference = value;
    }

    /**
     * Gets the value of the blpUentryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBLPUentryDate() {
        return blpUentryDate;
    }

    /**
     * Sets the value of the blpUentryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBLPUentryDate(XMLGregorianCalendar value) {
        this.blpUentryDate = value;
    }

    /**
     * Gets the value of the blpUstartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBLPUstartDate() {
        return blpUstartDate;
    }

    /**
     * Sets the value of the blpUstartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBLPUstartDate(XMLGregorianCalendar value) {
        this.blpUstartDate = value;
    }

    /**
     * Gets the value of the blpUendDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBLPUendDate() {
        return blpUendDate;
    }

    /**
     * Sets the value of the blpUendDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBLPUendDate(XMLGregorianCalendar value) {
        this.blpUendDate = value;
    }

    /**
     * Gets the value of the blpUlastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBLPUlastUpdateDate() {
        return blpUlastUpdateDate;
    }

    /**
     * Sets the value of the blpUlastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBLPUlastUpdateDate(XMLGregorianCalendar value) {
        this.blpUlastUpdateDate = value;
    }

    /**
     * Gets the value of the landAndPropertyIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the landAndPropertyIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLandAndPropertyIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LandAndPropertyIdentifierStructure }
     * 
     * 
     */
    public List<LandAndPropertyIdentifierStructure> getLandAndPropertyIdentifier() {
        if (landAndPropertyIdentifier == null) {
            landAndPropertyIdentifier = new ArrayList<LandAndPropertyIdentifierStructure>();
        }
        return this.landAndPropertyIdentifier;
    }

    /**
     * Gets the value of the provenance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the provenance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProvenance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProvenanceStructure }
     * 
     * 
     */
    public List<ProvenanceStructure> getProvenance() {
        if (provenance == null) {
            provenance = new ArrayList<ProvenanceStructure>();
        }
        return this.provenance;
    }

}
