//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BLPUextentStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BLPUextentStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SourceDescription">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ExtentEntryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ExtentSourceDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ExtentStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ExtentEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ExtentLastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ExtentDefinition" type="{http://www.govtalk.gov.uk/people/bs7666}BLPUpolygonStructure" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BLPUextentStructure", propOrder = {
    "sourceDescription",
    "extentEntryDate",
    "extentSourceDate",
    "extentStartDate",
    "extentEndDate",
    "extentLastUpdateDate",
    "extentDefinition"
})
public class BLPUextentStructure {

    @XmlElement(name = "SourceDescription", required = true)
    protected String sourceDescription;
    @XmlElement(name = "ExtentEntryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar extentEntryDate;
    @XmlElement(name = "ExtentSourceDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar extentSourceDate;
    @XmlElement(name = "ExtentStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar extentStartDate;
    @XmlElement(name = "ExtentEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar extentEndDate;
    @XmlElement(name = "ExtentLastUpdateDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar extentLastUpdateDate;
    @XmlElement(name = "ExtentDefinition", required = true)
    protected List<BLPUpolygonStructure> extentDefinition;

    /**
     * Gets the value of the sourceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDescription() {
        return sourceDescription;
    }

    /**
     * Sets the value of the sourceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDescription(String value) {
        this.sourceDescription = value;
    }

    /**
     * Gets the value of the extentEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtentEntryDate() {
        return extentEntryDate;
    }

    /**
     * Sets the value of the extentEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtentEntryDate(XMLGregorianCalendar value) {
        this.extentEntryDate = value;
    }

    /**
     * Gets the value of the extentSourceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtentSourceDate() {
        return extentSourceDate;
    }

    /**
     * Sets the value of the extentSourceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtentSourceDate(XMLGregorianCalendar value) {
        this.extentSourceDate = value;
    }

    /**
     * Gets the value of the extentStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtentStartDate() {
        return extentStartDate;
    }

    /**
     * Sets the value of the extentStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtentStartDate(XMLGregorianCalendar value) {
        this.extentStartDate = value;
    }

    /**
     * Gets the value of the extentEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtentEndDate() {
        return extentEndDate;
    }

    /**
     * Sets the value of the extentEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtentEndDate(XMLGregorianCalendar value) {
        this.extentEndDate = value;
    }

    /**
     * Gets the value of the extentLastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExtentLastUpdateDate() {
        return extentLastUpdateDate;
    }

    /**
     * Sets the value of the extentLastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExtentLastUpdateDate(XMLGregorianCalendar value) {
        this.extentLastUpdateDate = value;
    }

    /**
     * Gets the value of the extentDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extentDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtentDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BLPUpolygonStructure }
     * 
     * 
     */
    public List<BLPUpolygonStructure> getExtentDefinition() {
        if (extentDefinition == null) {
            extentDefinition = new ArrayList<BLPUpolygonStructure>();
        }
        return this.extentDefinition;
    }

}
