//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ElementaryStreetUnitStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementaryStreetUnitStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ESUidentity" type="{http://www.govtalk.gov.uk/people/bs7666}RefPointGridCoordinateType"/>
 *         &lt;element name="ESUversion" type="{http://www.govtalk.gov.uk/people/bs7666}VersionNumberType"/>
 *         &lt;element name="ESUentryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ESUclosureDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="StartCoordinate" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure"/>
 *         &lt;element name="EndCoordinate" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure"/>
 *         &lt;element name="Tolerance" type="{http://www.govtalk.gov.uk/people/bs7666}ToleranceType"/>
 *         &lt;element name="IntermediateCoord" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementaryStreetUnitStructure", propOrder = {
    "esUidentity",
    "esUversion",
    "esUentryDate",
    "esUclosureDate",
    "startCoordinate",
    "endCoordinate",
    "tolerance",
    "intermediateCoord"
})
public class ElementaryStreetUnitStructure {

    @XmlElement(name = "ESUidentity", required = true)
    protected String esUidentity;
    @XmlElement(name = "ESUversion")
    protected int esUversion;
    @XmlElement(name = "ESUentryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar esUentryDate;
    @XmlElement(name = "ESUclosureDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar esUclosureDate;
    @XmlElement(name = "StartCoordinate", required = true)
    protected CoordinateStructure startCoordinate;
    @XmlElement(name = "EndCoordinate", required = true)
    protected CoordinateStructure endCoordinate;
    @XmlElement(name = "Tolerance", required = true)
    protected BigDecimal tolerance;
    @XmlElement(name = "IntermediateCoord")
    protected List<CoordinateStructure> intermediateCoord;

    /**
     * Gets the value of the esUidentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESUidentity() {
        return esUidentity;
    }

    /**
     * Sets the value of the esUidentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESUidentity(String value) {
        this.esUidentity = value;
    }

    /**
     * Gets the value of the esUversion property.
     * 
     */
    public int getESUversion() {
        return esUversion;
    }

    /**
     * Sets the value of the esUversion property.
     * 
     */
    public void setESUversion(int value) {
        this.esUversion = value;
    }

    /**
     * Gets the value of the esUentryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getESUentryDate() {
        return esUentryDate;
    }

    /**
     * Sets the value of the esUentryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setESUentryDate(XMLGregorianCalendar value) {
        this.esUentryDate = value;
    }

    /**
     * Gets the value of the esUclosureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getESUclosureDate() {
        return esUclosureDate;
    }

    /**
     * Sets the value of the esUclosureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setESUclosureDate(XMLGregorianCalendar value) {
        this.esUclosureDate = value;
    }

    /**
     * Gets the value of the startCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateStructure }
     *     
     */
    public CoordinateStructure getStartCoordinate() {
        return startCoordinate;
    }

    /**
     * Sets the value of the startCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateStructure }
     *     
     */
    public void setStartCoordinate(CoordinateStructure value) {
        this.startCoordinate = value;
    }

    /**
     * Gets the value of the endCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateStructure }
     *     
     */
    public CoordinateStructure getEndCoordinate() {
        return endCoordinate;
    }

    /**
     * Sets the value of the endCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateStructure }
     *     
     */
    public void setEndCoordinate(CoordinateStructure value) {
        this.endCoordinate = value;
    }

    /**
     * Gets the value of the tolerance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTolerance() {
        return tolerance;
    }

    /**
     * Sets the value of the tolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTolerance(BigDecimal value) {
        this.tolerance = value;
    }

    /**
     * Gets the value of the intermediateCoord property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intermediateCoord property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntermediateCoord().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoordinateStructure }
     * 
     * 
     */
    public List<CoordinateStructure> getIntermediateCoord() {
        if (intermediateCoord == null) {
            intermediateCoord = new ArrayList<CoordinateStructure>();
        }
        return this.intermediateCoord;
    }

}
