//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LandAndPropertyIdentifierStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LandAndPropertyIdentifierStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PAON" type="{http://www.govtalk.gov.uk/people/bs7666}PAONtype"/>
 *         &lt;element name="SAON" type="{http://www.govtalk.gov.uk/people/bs7666}SAONtype" minOccurs="0"/>
 *         &lt;element name="PostTown" type="{http://www.govtalk.gov.uk/people/bs7666}PostTownType" minOccurs="0"/>
 *         &lt;element name="PostCode" type="{http://www.govtalk.gov.uk/people/bs7666}PostCodeType" minOccurs="0"/>
 *         &lt;element name="Level" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LogicalStatus" type="{http://www.govtalk.gov.uk/people/bs7666}LogicalStatusType"/>
 *         &lt;element name="OfficialAddressMarker" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LPIstartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LPIentryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="LPIendDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="LPIlastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;choice>
 *           &lt;element name="Street" type="{http://www.govtalk.gov.uk/people/bs7666}StreetStructure"/>
 *           &lt;element name="USRN" type="{http://www.govtalk.gov.uk/people/bs7666}USRNtype"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LandAndPropertyIdentifierStructure", propOrder = {
    "paon",
    "saon",
    "postTown",
    "postCode",
    "level",
    "logicalStatus",
    "officialAddressMarker",
    "lpIstartDate",
    "lpIentryDate",
    "lpIendDate",
    "lpIlastUpdateDate",
    "street",
    "usrn"
})
public class LandAndPropertyIdentifierStructure {

    @XmlElement(name = "PAON", required = true)
    protected String paon;
    @XmlElement(name = "SAON")
    protected String saon;
    @XmlElement(name = "PostTown")
    protected String postTown;
    @XmlElement(name = "PostCode")
    protected String postCode;
    @XmlElement(name = "Level")
    protected String level;
    @XmlElement(name = "LogicalStatus")
    protected int logicalStatus;
    @XmlElement(name = "OfficialAddressMarker")
    protected Boolean officialAddressMarker;
    @XmlElement(name = "LPIstartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lpIstartDate;
    @XmlElement(name = "LPIentryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lpIentryDate;
    @XmlElement(name = "LPIendDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lpIendDate;
    @XmlElement(name = "LPIlastUpdateDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lpIlastUpdateDate;
    @XmlElement(name = "Street")
    protected StreetStructure street;
    @XmlElement(name = "USRN")
    protected Integer usrn;

    /**
     * Gets the value of the paon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAON() {
        return paon;
    }

    /**
     * Sets the value of the paon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAON(String value) {
        this.paon = value;
    }

    /**
     * Gets the value of the saon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAON() {
        return saon;
    }

    /**
     * Sets the value of the saon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAON(String value) {
        this.saon = value;
    }

    /**
     * Gets the value of the postTown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostTown() {
        return postTown;
    }

    /**
     * Sets the value of the postTown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostTown(String value) {
        this.postTown = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the logicalStatus property.
     * 
     */
    public int getLogicalStatus() {
        return logicalStatus;
    }

    /**
     * Sets the value of the logicalStatus property.
     * 
     */
    public void setLogicalStatus(int value) {
        this.logicalStatus = value;
    }

    /**
     * Gets the value of the officialAddressMarker property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOfficialAddressMarker() {
        return officialAddressMarker;
    }

    /**
     * Sets the value of the officialAddressMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOfficialAddressMarker(Boolean value) {
        this.officialAddressMarker = value;
    }

    /**
     * Gets the value of the lpIstartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLPIstartDate() {
        return lpIstartDate;
    }

    /**
     * Sets the value of the lpIstartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLPIstartDate(XMLGregorianCalendar value) {
        this.lpIstartDate = value;
    }

    /**
     * Gets the value of the lpIentryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLPIentryDate() {
        return lpIentryDate;
    }

    /**
     * Sets the value of the lpIentryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLPIentryDate(XMLGregorianCalendar value) {
        this.lpIentryDate = value;
    }

    /**
     * Gets the value of the lpIendDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLPIendDate() {
        return lpIendDate;
    }

    /**
     * Sets the value of the lpIendDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLPIendDate(XMLGregorianCalendar value) {
        this.lpIendDate = value;
    }

    /**
     * Gets the value of the lpIlastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLPIlastUpdateDate() {
        return lpIlastUpdateDate;
    }

    /**
     * Sets the value of the lpIlastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLPIlastUpdateDate(XMLGregorianCalendar value) {
        this.lpIlastUpdateDate = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link StreetStructure }
     *     
     */
    public StreetStructure getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetStructure }
     *     
     */
    public void setStreet(StreetStructure value) {
        this.street = value;
    }

    /**
     * Gets the value of the usrn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUSRN() {
        return usrn;
    }

    /**
     * Sets the value of the usrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUSRN(Integer value) {
        this.usrn = value;
    }

}
