//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.govtalk.people.bs7666 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BS7666Address_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "BS7666Address");
    private final static QName _Locality_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "Locality");
    private final static QName _Town_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "Town");
    private final static QName _BS7666BLPU_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "BS7666BLPU");
    private final static QName _AdministrativeArea_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "AdministrativeArea");
    private final static QName _UniquePropertyReferenceNumber_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "UniquePropertyReferenceNumber");
    private final static QName _BSaddressStructurePostTown_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "PostTown");
    private final static QName _BSaddressStructureStreetDescription_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "StreetDescription");
    private final static QName _BSaddressStructurePostCode_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "PostCode");
    private final static QName _BSaddressStructurePAON_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "PAON");
    private final static QName _BSaddressStructureUniqueStreetReferenceNumber_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "UniqueStreetReferenceNumber");
    private final static QName _BSaddressStructureSAON_QNAME = new QName("http://www.govtalk.gov.uk/people/bs7666", "SAON");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.govtalk.people.bs7666
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StreetDescriptiveIdentifierStructure }
     * 
     */
    public StreetDescriptiveIdentifierStructure createStreetDescriptiveIdentifierStructure() {
        return new StreetDescriptiveIdentifierStructure();
    }

    /**
     * Create an instance of {@link StreetStructure.StreetCrossReferences }
     * 
     */
    public StreetStructure.StreetCrossReferences createStreetStructureStreetCrossReferences() {
        return new StreetStructure.StreetCrossReferences();
    }

    /**
     * Create an instance of {@link CoordinateStructure }
     * 
     */
    public CoordinateStructure createCoordinateStructure() {
        return new CoordinateStructure();
    }

    /**
     * Create an instance of {@link BLPUextentStructure }
     * 
     */
    public BLPUextentStructure createBLPUextentStructure() {
        return new BLPUextentStructure();
    }

    /**
     * Create an instance of {@link StreetStructure }
     * 
     */
    public StreetStructure createStreetStructure() {
        return new StreetStructure();
    }

    /**
     * Create an instance of {@link BasicLandAndPropertyUnitStructure }
     * 
     */
    public BasicLandAndPropertyUnitStructure createBasicLandAndPropertyUnitStructure() {
        return new BasicLandAndPropertyUnitStructure();
    }

    /**
     * Create an instance of {@link BSaddressStructure }
     * 
     */
    public BSaddressStructure createBSaddressStructure() {
        return new BSaddressStructure();
    }

    /**
     * Create an instance of {@link BLPUpolygonStructure }
     * 
     */
    public BLPUpolygonStructure createBLPUpolygonStructure() {
        return new BLPUpolygonStructure();
    }

    /**
     * Create an instance of {@link ProvenanceStructure }
     * 
     */
    public ProvenanceStructure createProvenanceStructure() {
        return new ProvenanceStructure();
    }

    /**
     * Create an instance of {@link ElementaryStreetUnitStructure }
     * 
     */
    public ElementaryStreetUnitStructure createElementaryStreetUnitStructure() {
        return new ElementaryStreetUnitStructure();
    }

    /**
     * Create an instance of {@link LandAndPropertyIdentifierStructure }
     * 
     */
    public LandAndPropertyIdentifierStructure createLandAndPropertyIdentifierStructure() {
        return new LandAndPropertyIdentifierStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BSaddressStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "BS7666Address")
    public JAXBElement<BSaddressStructure> createBS7666Address(BSaddressStructure value) {
        return new JAXBElement<BSaddressStructure>(_BS7666Address_QNAME, BSaddressStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "Locality")
    public JAXBElement<String> createLocality(String value) {
        return new JAXBElement<String>(_Locality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "Town")
    public JAXBElement<String> createTown(String value) {
        return new JAXBElement<String>(_Town_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicLandAndPropertyUnitStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "BS7666BLPU")
    public JAXBElement<BasicLandAndPropertyUnitStructure> createBS7666BLPU(BasicLandAndPropertyUnitStructure value) {
        return new JAXBElement<BasicLandAndPropertyUnitStructure>(_BS7666BLPU_QNAME, BasicLandAndPropertyUnitStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "AdministrativeArea")
    public JAXBElement<String> createAdministrativeArea(String value) {
        return new JAXBElement<String>(_AdministrativeArea_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "UniquePropertyReferenceNumber")
    public JAXBElement<Long> createUniquePropertyReferenceNumber(Long value) {
        return new JAXBElement<Long>(_UniquePropertyReferenceNumber_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "PostTown", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructurePostTown(String value) {
        return new JAXBElement<String>(_BSaddressStructurePostTown_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "StreetDescription", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructureStreetDescription(String value) {
        return new JAXBElement<String>(_BSaddressStructureStreetDescription_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "PostCode", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructurePostCode(String value) {
        return new JAXBElement<String>(_BSaddressStructurePostCode_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "PAON", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructurePAON(String value) {
        return new JAXBElement<String>(_BSaddressStructurePAON_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "UniquePropertyReferenceNumber", scope = BSaddressStructure.class)
    public JAXBElement<Long> createBSaddressStructureUniquePropertyReferenceNumber(Long value) {
        return new JAXBElement<Long>(_UniquePropertyReferenceNumber_QNAME, Long.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "UniqueStreetReferenceNumber", scope = BSaddressStructure.class)
    public JAXBElement<Integer> createBSaddressStructureUniqueStreetReferenceNumber(Integer value) {
        return new JAXBElement<Integer>(_BSaddressStructureUniqueStreetReferenceNumber_QNAME, Integer.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "SAON", scope = BSaddressStructure.class)
    public JAXBElement<String> createBSaddressStructureSAON(String value) {
        return new JAXBElement<String>(_BSaddressStructureSAON_QNAME, String.class, BSaddressStructure.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.govtalk.gov.uk/people/bs7666", name = "StreetDescription", scope = StreetDescriptiveIdentifierStructure.class)
    public JAXBElement<String> createStreetDescriptiveIdentifierStructureStreetDescription(String value) {
        return new JAXBElement<String>(_BSaddressStructureStreetDescription_QNAME, String.class, StreetDescriptiveIdentifierStructure.class, value);
    }

}
