//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProvenanceStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProvenanceStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProvenanceCode" type="{http://www.govtalk.gov.uk/people/bs7666}ProvenanceCodeType"/>
 *         &lt;element name="Annotation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProvEntryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ProvStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ProvEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ProvLastUpdateDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="BLPUextent" type="{http://www.govtalk.gov.uk/people/bs7666}BLPUextentStructure" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProvenanceStructure", propOrder = {
    "provenanceCode",
    "annotation",
    "provEntryDate",
    "provStartDate",
    "provEndDate",
    "provLastUpdateDate",
    "blpUextent"
})
public class ProvenanceStructure {

    @XmlElement(name = "ProvenanceCode", required = true)
    protected ProvenanceCodeType provenanceCode;
    @XmlElement(name = "Annotation", required = true)
    protected String annotation;
    @XmlElement(name = "ProvEntryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provEntryDate;
    @XmlElement(name = "ProvStartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provStartDate;
    @XmlElement(name = "ProvEndDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provEndDate;
    @XmlElement(name = "ProvLastUpdateDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar provLastUpdateDate;
    @XmlElement(name = "BLPUextent")
    protected BLPUextentStructure blpUextent;

    /**
     * Gets the value of the provenanceCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProvenanceCodeType }
     *     
     */
    public ProvenanceCodeType getProvenanceCode() {
        return provenanceCode;
    }

    /**
     * Sets the value of the provenanceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvenanceCodeType }
     *     
     */
    public void setProvenanceCode(ProvenanceCodeType value) {
        this.provenanceCode = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the provEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProvEntryDate() {
        return provEntryDate;
    }

    /**
     * Sets the value of the provEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProvEntryDate(XMLGregorianCalendar value) {
        this.provEntryDate = value;
    }

    /**
     * Gets the value of the provStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProvStartDate() {
        return provStartDate;
    }

    /**
     * Sets the value of the provStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProvStartDate(XMLGregorianCalendar value) {
        this.provStartDate = value;
    }

    /**
     * Gets the value of the provEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProvEndDate() {
        return provEndDate;
    }

    /**
     * Sets the value of the provEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProvEndDate(XMLGregorianCalendar value) {
        this.provEndDate = value;
    }

    /**
     * Gets the value of the provLastUpdateDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getProvLastUpdateDate() {
        return provLastUpdateDate;
    }

    /**
     * Sets the value of the provLastUpdateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProvLastUpdateDate(XMLGregorianCalendar value) {
        this.provLastUpdateDate = value;
    }

    /**
     * Gets the value of the blpUextent property.
     * 
     * @return
     *     possible object is
     *     {@link BLPUextentStructure }
     *     
     */
    public BLPUextentStructure getBLPUextent() {
        return blpUextent;
    }

    /**
     * Sets the value of the blpUextent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLPUextentStructure }
     *     
     */
    public void setBLPUextent(BLPUextentStructure value) {
        this.blpUextent = value;
    }

}
