//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProvenanceCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProvenanceCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="P"/>
 *     &lt;enumeration value="O"/>
 *     &lt;enumeration value="U"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProvenanceCodeType")
@XmlEnum
public enum ProvenanceCodeType {

    T,
    L,
    F,
    R,
    P,
    O,
    U;

    public String value() {
        return name();
    }

    public static ProvenanceCodeType fromValue(String v) {
        return valueOf(v);
    }

}
