//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 02:49:41 PM AST 
//


package uk.gov.govtalk.people.bs7666;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for StreetStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StreetStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StreetReferenceType" type="{http://www.govtalk.gov.uk/people/bs7666}StreetReferenceTypeType"/>
 *         &lt;element name="StartCoordinate" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure"/>
 *         &lt;element name="EndCoordinate" type="{http://www.govtalk.gov.uk/people/bs7666}CoordinateStructure"/>
 *         &lt;element name="Tolerance" type="{http://www.govtalk.gov.uk/people/bs7666}ToleranceType"/>
 *         &lt;element name="StreetVersionNumber" type="{http://www.govtalk.gov.uk/people/bs7666}VersionNumberType"/>
 *         &lt;element name="StreetEntryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="StreetClosureDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ResponsibleAuthority" type="{http://www.govtalk.gov.uk/people/bs7666}CustodianCodeType"/>
 *         &lt;element name="DescriptiveIdentifier" type="{http://www.govtalk.gov.uk/people/bs7666}StreetDescriptiveIdentifierStructure"/>
 *         &lt;element name="StreetAlias" type="{http://www.govtalk.gov.uk/people/bs7666}StreetDescriptiveIdentifierStructure" minOccurs="0"/>
 *         &lt;element name="StreetCrossReferences" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="UNIQUE_STREET_REFERENCE_NUMBERS" type="{http://www.govtalk.gov.uk/people/bs7666}USRNlistType"/>
 *                   &lt;element name="ElementaryStreetUnit" type="{http://www.govtalk.gov.uk/people/bs7666}ElementaryStreetUnitStructure" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="usrn" type="{http://www.govtalk.gov.uk/people/bs7666}USRNtype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StreetStructure", propOrder = {
    "streetReferenceType",
    "startCoordinate",
    "endCoordinate",
    "tolerance",
    "streetVersionNumber",
    "streetEntryDate",
    "streetClosureDate",
    "responsibleAuthority",
    "descriptiveIdentifier",
    "streetAlias",
    "streetCrossReferences"
})
public class StreetStructure {

    @XmlElement(name = "StreetReferenceType", required = true)
    protected BigInteger streetReferenceType;
    @XmlElement(name = "StartCoordinate", required = true)
    protected CoordinateStructure startCoordinate;
    @XmlElement(name = "EndCoordinate", required = true)
    protected CoordinateStructure endCoordinate;
    @XmlElement(name = "Tolerance", required = true)
    protected BigDecimal tolerance;
    @XmlElement(name = "StreetVersionNumber")
    protected int streetVersionNumber;
    @XmlElement(name = "StreetEntryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar streetEntryDate;
    @XmlElement(name = "StreetClosureDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar streetClosureDate;
    @XmlElement(name = "ResponsibleAuthority")
    protected int responsibleAuthority;
    @XmlElement(name = "DescriptiveIdentifier", required = true)
    protected StreetDescriptiveIdentifierStructure descriptiveIdentifier;
    @XmlElement(name = "StreetAlias")
    protected StreetDescriptiveIdentifierStructure streetAlias;
    @XmlElement(name = "StreetCrossReferences")
    protected StreetStructure.StreetCrossReferences streetCrossReferences;
    @XmlAttribute
    protected Integer usrn;

    /**
     * Gets the value of the streetReferenceType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStreetReferenceType() {
        return streetReferenceType;
    }

    /**
     * Sets the value of the streetReferenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStreetReferenceType(BigInteger value) {
        this.streetReferenceType = value;
    }

    /**
     * Gets the value of the startCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateStructure }
     *     
     */
    public CoordinateStructure getStartCoordinate() {
        return startCoordinate;
    }

    /**
     * Sets the value of the startCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateStructure }
     *     
     */
    public void setStartCoordinate(CoordinateStructure value) {
        this.startCoordinate = value;
    }

    /**
     * Gets the value of the endCoordinate property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateStructure }
     *     
     */
    public CoordinateStructure getEndCoordinate() {
        return endCoordinate;
    }

    /**
     * Sets the value of the endCoordinate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateStructure }
     *     
     */
    public void setEndCoordinate(CoordinateStructure value) {
        this.endCoordinate = value;
    }

    /**
     * Gets the value of the tolerance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTolerance() {
        return tolerance;
    }

    /**
     * Sets the value of the tolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTolerance(BigDecimal value) {
        this.tolerance = value;
    }

    /**
     * Gets the value of the streetVersionNumber property.
     * 
     */
    public int getStreetVersionNumber() {
        return streetVersionNumber;
    }

    /**
     * Sets the value of the streetVersionNumber property.
     * 
     */
    public void setStreetVersionNumber(int value) {
        this.streetVersionNumber = value;
    }

    /**
     * Gets the value of the streetEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStreetEntryDate() {
        return streetEntryDate;
    }

    /**
     * Sets the value of the streetEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStreetEntryDate(XMLGregorianCalendar value) {
        this.streetEntryDate = value;
    }

    /**
     * Gets the value of the streetClosureDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStreetClosureDate() {
        return streetClosureDate;
    }

    /**
     * Sets the value of the streetClosureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStreetClosureDate(XMLGregorianCalendar value) {
        this.streetClosureDate = value;
    }

    /**
     * Gets the value of the responsibleAuthority property.
     * 
     */
    public int getResponsibleAuthority() {
        return responsibleAuthority;
    }

    /**
     * Sets the value of the responsibleAuthority property.
     * 
     */
    public void setResponsibleAuthority(int value) {
        this.responsibleAuthority = value;
    }

    /**
     * Gets the value of the descriptiveIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link StreetDescriptiveIdentifierStructure }
     *     
     */
    public StreetDescriptiveIdentifierStructure getDescriptiveIdentifier() {
        return descriptiveIdentifier;
    }

    /**
     * Sets the value of the descriptiveIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetDescriptiveIdentifierStructure }
     *     
     */
    public void setDescriptiveIdentifier(StreetDescriptiveIdentifierStructure value) {
        this.descriptiveIdentifier = value;
    }

    /**
     * Gets the value of the streetAlias property.
     * 
     * @return
     *     possible object is
     *     {@link StreetDescriptiveIdentifierStructure }
     *     
     */
    public StreetDescriptiveIdentifierStructure getStreetAlias() {
        return streetAlias;
    }

    /**
     * Sets the value of the streetAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetDescriptiveIdentifierStructure }
     *     
     */
    public void setStreetAlias(StreetDescriptiveIdentifierStructure value) {
        this.streetAlias = value;
    }

    /**
     * Gets the value of the streetCrossReferences property.
     * 
     * @return
     *     possible object is
     *     {@link StreetStructure.StreetCrossReferences }
     *     
     */
    public StreetStructure.StreetCrossReferences getStreetCrossReferences() {
        return streetCrossReferences;
    }

    /**
     * Sets the value of the streetCrossReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreetStructure.StreetCrossReferences }
     *     
     */
    public void setStreetCrossReferences(StreetStructure.StreetCrossReferences value) {
        this.streetCrossReferences = value;
    }

    /**
     * Gets the value of the usrn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsrn() {
        return usrn;
    }

    /**
     * Sets the value of the usrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsrn(Integer value) {
        this.usrn = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="UNIQUE_STREET_REFERENCE_NUMBERS" type="{http://www.govtalk.gov.uk/people/bs7666}USRNlistType"/>
     *         &lt;element name="ElementaryStreetUnit" type="{http://www.govtalk.gov.uk/people/bs7666}ElementaryStreetUnitStructure" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uniquestreetreferencenumbers",
        "elementaryStreetUnit"
    })
    public static class StreetCrossReferences {

        @XmlList
        @XmlElement(name = "UNIQUE_STREET_REFERENCE_NUMBERS", type = Integer.class)
        protected List<Integer> uniquestreetreferencenumbers;
        @XmlElement(name = "ElementaryStreetUnit")
        protected List<ElementaryStreetUnitStructure> elementaryStreetUnit;

        /**
         * Gets the value of the uniquestreetreferencenumbers property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the uniquestreetreferencenumbers property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUNIQUESTREETREFERENCENUMBERS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getUNIQUESTREETREFERENCENUMBERS() {
            if (uniquestreetreferencenumbers == null) {
                uniquestreetreferencenumbers = new ArrayList<Integer>();
            }
            return this.uniquestreetreferencenumbers;
        }

        /**
         * Gets the value of the elementaryStreetUnit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the elementaryStreetUnit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementaryStreetUnit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ElementaryStreetUnitStructure }
         * 
         * 
         */
        public List<ElementaryStreetUnitStructure> getElementaryStreetUnit() {
            if (elementaryStreetUnit == null) {
                elementaryStreetUnit = new ArrayList<ElementaryStreetUnitStructure>();
            }
            return this.elementaryStreetUnit;
        }

    }

}
